// ETVMGlueCheck.c — ETVMBytecode.h の番号が WDL の glue_port.h（EEL_BC_*）と同じかを建てるときに確かめる。
// 中身は _Static_assert と命令の名前の表だけ（glue_port.h の静的な関数・表は使わない）。
// JIT の建て方（Tools/jsfx-bench の wdl-jit）でも番号を確かめられるように、この TU だけ portable の宣言を読む。
#ifndef EEL_TARGET_PORTABLE
#define EEL_TARGET_PORTABLE
#endif
#include "ETVMBytecode.h"

#include "WDL/eel2/ns-eel-int.h"
#include "WDL/denormal.h"
#include <math.h>
#include <string.h>

#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-function"
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-const-variable"
#endif
// glue_port.h は _asm_generic* を外へ出す（BC_DECLASM_N_EXPORT）。nseel-compiler.c とぶつからない名前にする。
#define _asm_generic1parm etvm_glue_check_generic1parm
#define _asm_generic2parm etvm_glue_check_generic2parm
#define _asm_generic3parm etvm_glue_check_generic3parm
#define _asm_generic1parm_retd etvm_glue_check_generic1parm_retd
#define _asm_generic2parm_retd etvm_glue_check_generic2parm_retd
#define _asm_generic2xparm_retd etvm_glue_check_generic2xparm_retd
#define _asm_generic3parm_retd etvm_glue_check_generic3parm_retd
#include "WDL/eel2/glue_port.h"
#if defined(__clang__)
#pragma clang diagnostic pop
#endif

#if !(NSEEL_LOOPFUNC_SUPPORT_MAXLEN > 0)
#error "ETVM は WHILE_SETUP の在る建て方（NSEEL_LOOPFUNC_SUPPORT_MAXLEN > 0）だけ読む"
#endif

#define ETVM_SAME(x) _Static_assert((int)ETBC_##x == (int)EEL_BC_##x, "ETBC_" #x " != EEL_BC_" #x);
ETVM_SAME(NOP) ETVM_SAME(RET) ETVM_SAME(JMP_NC) ETVM_SAME(JMP_IF_P1_Z) ETVM_SAME(JMP_IF_P1_NZ)
ETVM_SAME(MOV_FPTOP_DV) ETVM_SAME(MOV_P1_DV) ETVM_SAME(MOV_P2_DV) ETVM_SAME(MOV_P3_DV) ETVM_SAME(_RESET_WTP)
ETVM_SAME(PUSH_P1) ETVM_SAME(PUSH_P1PTR_AS_VALUE) ETVM_SAME(POP_P1) ETVM_SAME(POP_P2) ETVM_SAME(POP_P3)
ETVM_SAME(POP_VALUE_TO_ADDR) ETVM_SAME(MOVE_STACK) ETVM_SAME(STORE_P1_TO_STACK_AT_OFFS)
ETVM_SAME(MOVE_STACKPTR_TO_P1) ETVM_SAME(MOVE_STACKPTR_TO_P2) ETVM_SAME(MOVE_STACKPTR_TO_P3)
ETVM_SAME(SET_P2_FROM_P1) ETVM_SAME(SET_P3_FROM_P1) ETVM_SAME(COPY_VALUE_AT_P1_TO_ADDR)
ETVM_SAME(SET_P1_FROM_WTP) ETVM_SAME(SET_P2_FROM_WTP) ETVM_SAME(SET_P3_FROM_WTP)
ETVM_SAME(POP_FPSTACK_TO_PTR) ETVM_SAME(POP_FPSTACK_TOSTACK) ETVM_SAME(PUSH_VAL_AT_P1_TO_FPSTACK)
ETVM_SAME(PUSH_VAL_AT_P2_TO_FPSTACK) ETVM_SAME(PUSH_VAL_AT_P3_TO_FPSTACK) ETVM_SAME(POP_FPSTACK_TO_WTP)
ETVM_SAME(SET_P1_Z) ETVM_SAME(SET_P1_NZ) ETVM_SAME(LOOP_LOADCNT) ETVM_SAME(LOOP_END) ETVM_SAME(WHILE_SETUP)
ETVM_SAME(WHILE_BEGIN) ETVM_SAME(WHILE_END) ETVM_SAME(WHILE_CHECK_RV) ETVM_SAME(BNOT) ETVM_SAME(EQUAL)
ETVM_SAME(EQUAL_EXACT) ETVM_SAME(NOTEQUAL) ETVM_SAME(NOTEQUAL_EXACT) ETVM_SAME(ABOVE) ETVM_SAME(BELOWEQ)
ETVM_SAME(ADD) ETVM_SAME(SUB) ETVM_SAME(MUL) ETVM_SAME(DIV) ETVM_SAME(AND) ETVM_SAME(OR) ETVM_SAME(OR0)
ETVM_SAME(XOR) ETVM_SAME(ADD_OP) ETVM_SAME(SUB_OP) ETVM_SAME(ADD_OP_FAST) ETVM_SAME(SUB_OP_FAST)
ETVM_SAME(MUL_OP) ETVM_SAME(DIV_OP) ETVM_SAME(MUL_OP_FAST) ETVM_SAME(DIV_OP_FAST) ETVM_SAME(AND_OP)
ETVM_SAME(OR_OP) ETVM_SAME(XOR_OP) ETVM_SAME(UMINUS) ETVM_SAME(ASSIGN) ETVM_SAME(ASSIGN_FAST)
ETVM_SAME(ASSIGN_FAST_FROMFP) ETVM_SAME(ASSIGN_FROMFP) ETVM_SAME(MOD) ETVM_SAME(MOD_OP) ETVM_SAME(SHR)
ETVM_SAME(SHL) ETVM_SAME(SQR) ETVM_SAME(MIN) ETVM_SAME(MAX) ETVM_SAME(MIN_FP) ETVM_SAME(MAX_FP)
ETVM_SAME(ABS) ETVM_SAME(SIGN) ETVM_SAME(INVSQRT) ETVM_SAME(FXCH) ETVM_SAME(POP_FPSTACK) ETVM_SAME(FCALL)
ETVM_SAME(BOOLTOFP) ETVM_SAME(FPTOBOOL) ETVM_SAME(FPTOBOOL_REV) ETVM_SAME(CFUNC_1PDD) ETVM_SAME(CFUNC_2PDD)
ETVM_SAME(CFUNC_2PDDS) ETVM_SAME(MEGABUF) ETVM_SAME(GMEGABUF) ETVM_SAME(GENERIC1PARM) ETVM_SAME(GENERIC2PARM)
ETVM_SAME(GENERIC3PARM) ETVM_SAME(GENERIC1PARM_RETD) ETVM_SAME(GENERIC2PARM_RETD)
ETVM_SAME(GENERIC2XPARM_RETD) ETVM_SAME(GENERIC3PARM_RETD) ETVM_SAME(USERSTACK_PUSH) ETVM_SAME(USERSTACK_POP)
ETVM_SAME(USERSTACK_POPFAST) ETVM_SAME(USERSTACK_PEEK) ETVM_SAME(USERSTACK_PEEK_INT)
ETVM_SAME(USERSTACK_PEEK_TOP) ETVM_SAME(USERSTACK_EXCH) ETVM_SAME(DBG_GETSTACKPTR)
#undef ETVM_SAME

// 即値の幅も glue_port.h の BC_DECLASM_N の個数と同じか（関数呼び・メモリ・積み場の命令）。
_Static_assert(sizeof(EEL_BC_TYPE) == 4, "EEL_BC_TYPE is int");
_Static_assert(sizeof(INT_PTR) == 8, "64-bit only");
_Static_assert(sizeof(GLUE_JMP_TYPE) == 4, "jump offsets are int");

const char *etbc_name(int op)
{
#define N(x) [ETBC_##x] = #x,
    static const char *const names[ETBC_COUNT] = {
        N(NOP) N(RET) N(JMP_NC) N(JMP_IF_P1_Z) N(JMP_IF_P1_NZ) N(MOV_FPTOP_DV) N(MOV_P1_DV) N(MOV_P2_DV)
        N(MOV_P3_DV) N(_RESET_WTP) N(PUSH_P1) N(PUSH_P1PTR_AS_VALUE) N(POP_P1) N(POP_P2) N(POP_P3)
        N(POP_VALUE_TO_ADDR) N(MOVE_STACK) N(STORE_P1_TO_STACK_AT_OFFS) N(MOVE_STACKPTR_TO_P1)
        N(MOVE_STACKPTR_TO_P2) N(MOVE_STACKPTR_TO_P3) N(SET_P2_FROM_P1) N(SET_P3_FROM_P1)
        N(COPY_VALUE_AT_P1_TO_ADDR) N(SET_P1_FROM_WTP) N(SET_P2_FROM_WTP) N(SET_P3_FROM_WTP)
        N(POP_FPSTACK_TO_PTR) N(POP_FPSTACK_TOSTACK) N(PUSH_VAL_AT_P1_TO_FPSTACK) N(PUSH_VAL_AT_P2_TO_FPSTACK)
        N(PUSH_VAL_AT_P3_TO_FPSTACK) N(POP_FPSTACK_TO_WTP) N(SET_P1_Z) N(SET_P1_NZ) N(LOOP_LOADCNT) N(LOOP_END)
        N(WHILE_SETUP) N(WHILE_BEGIN) N(WHILE_END) N(WHILE_CHECK_RV) N(BNOT) N(EQUAL) N(EQUAL_EXACT)
        N(NOTEQUAL) N(NOTEQUAL_EXACT) N(ABOVE) N(BELOWEQ) N(ADD) N(SUB) N(MUL) N(DIV) N(AND) N(OR) N(OR0)
        N(XOR) N(ADD_OP) N(SUB_OP) N(ADD_OP_FAST) N(SUB_OP_FAST) N(MUL_OP) N(DIV_OP) N(MUL_OP_FAST)
        N(DIV_OP_FAST) N(AND_OP) N(OR_OP) N(XOR_OP) N(UMINUS) N(ASSIGN) N(ASSIGN_FAST) N(ASSIGN_FAST_FROMFP)
        N(ASSIGN_FROMFP) N(MOD) N(MOD_OP) N(SHR) N(SHL) N(SQR) N(MIN) N(MAX) N(MIN_FP) N(MAX_FP) N(ABS)
        N(SIGN) N(INVSQRT) N(FXCH) N(POP_FPSTACK) N(FCALL) N(BOOLTOFP) N(FPTOBOOL) N(FPTOBOOL_REV)
        N(CFUNC_1PDD) N(CFUNC_2PDD) N(CFUNC_2PDDS) N(MEGABUF) N(GMEGABUF) N(GENERIC1PARM) N(GENERIC2PARM)
        N(GENERIC3PARM) N(GENERIC1PARM_RETD) N(GENERIC2PARM_RETD) N(GENERIC2XPARM_RETD) N(GENERIC3PARM_RETD)
        N(USERSTACK_PUSH) N(USERSTACK_POP) N(USERSTACK_POPFAST) N(USERSTACK_PEEK) N(USERSTACK_PEEK_INT)
        N(USERSTACK_PEEK_TOP) N(USERSTACK_EXCH) N(DBG_GETSTACKPTR)
    };
#undef N
    return (op > 0 && op < ETBC_COUNT && names[op]) ? names[op] : "?";
}
